---

- name: "Listing unused existing volume created by kubelet"
  shell: |
    mount | grep tmpfs| grep '/var/lib/kubelet' | awk {' print $3 '}
  register: results

- name: "Create list of volume"
  set_fact:
    block_devices: "{{ block_devices|default([]) + [ item ] }}"
  loop: "{{ results.stdout_lines }}" 

- name: "Unmounting unused existing volume created by kubelet"
  mount: 
    path: "{{ item }}"
    state: unmounted   
  with_items: 
    - "{{ block_devices }}"
    - /var/lib/kubelet
    - /var/lib/rancher
  
- name: "Make Container Network Interface down"
  shell: |
    if /sbin/ethtool "{{ item }}" | grep -q "Link detected: yes"; then
      ip link delete "{{ item }}"
      echo Interface "{{ item }} delete successfully . . ."
    else 
      echo Interface "{{ item }}" not found, skipping . . . 
    fi
  register: iface_status  
  with_items:
    - flannel.1
    - cni0  

- name: "Removing Kubernetes config created by rancher"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ceph
    - /etc/cni
    - /etc/kubernetes
    - /opt/cni
    - /opt/rke
    - /run/secrets/kubernetes.io
    - /run/calico
    - /run/flannel
    - /var/lib/calico
    - /var/lib/etcd
    - /var/lib/cni
    - /var/lib/kubelet
    - /var/lib/rancher/rke/log
    - /var/log/containers
    - /var/log/kube-audit
    - /var/log/pods
    - /var/run/calico